# Generated by Django 3.2.7 on 2021-12-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookitem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_commnet', to='bookitem.book')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'Comment',
                'ordering': ['-created_on'],
            },
        ),
    ]
