# Generated by Django 3.2.4 on 2021-08-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('bookitem', '0001_initial'),
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcase',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bookitem.book', verbose_name='Book'),
        ),
    ]
