# Generated by Django 3.2.7 on 2021-09-14 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookitem', '0001_initial'),
        ('bookcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marked_chapter', to='bookitem.chapter', verbose_name='Chapter'),
        ),
    ]
