# Generated by Django 3.2.4 on 2021-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_plan',
            name='price_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='top_up_item',
            name='price_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
