# Generated by Django 3.2.4 on 2021-08-19 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_auto_20210724_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='Balance',
            new_name='balance',
        ),
    ]
