# Generated by Django 3.2.7 on 2021-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_balance_user_profile_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription_plan',
            options={'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles}'},
        ),
        migrations.RemoveField(
            model_name='subscription_plan',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='subscription_plan',
            name='num_available',
        ),
        migrations.AddField(
            model_name='subscription_plan',
            name='type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Sliver', 'Sliver'), ('Bronze', 'Bronze'), ('Free', 'Free')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='plan_status',
            field=models.CharField(choices=[('Active', 'VIP'), ('Inactive', 'Normal')], default='Inactive', max_length=20),
        ),
        migrations.AlterModelTable(
            name='subscription_plan',
            table='Subscription',
        ),
        migrations.AlterModelTable(
            name='user_profile',
            table='Profile',
        ),
    ]
