# Generated by Django 3.2.4 on 2021-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('completed', 'completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
