# Generated by Django 3.2.4 on 2021-08-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payment', '0007_order_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[('unpaid', 'unpaid'), ('completed', 'completed'), ('cancelled', 'Cancelled')],
                default='unpaid', max_length=20),
        ),
    ]
