# Generated by Django 3.2.7 on 2021-12-19 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Author'), (4, 'Admin'), (3, 'Editor'), (1, 'Reader')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c27c3ba8-715b-42ed-b969-391cbba8deda'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
