# Generated by Django 3.2.3 on 2021-06-02 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='AuthUser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reader'), (3, 'Editor'), (4, 'Admin'), (2, 'Author')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='AuthUser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ff956de8-62bf-476e-bb26-965fc308c58a'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
        migrations.AlterModelTable(
            name='AuthUser',
            table='AuthUser',
        ),
    ]
