# Generated by Django 3.2.7 on 2021-12-23 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reader'), (3, 'Editor'), (4, 'Admin'), (2, 'Author')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('545c7ea9-d329-4218-9760-10a4a9db913f'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
