# Generated by Django 3.2.7 on 2021-12-23 23:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211223_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reader'), (3, 'Editor'), (2, 'Author'), (4, 'Admin')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('63608cd5-66dd-4ef6-9428-26abc3c7b87d'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
