# Generated by Django 3.2.4 on 2021-07-21 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20210704_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'Reader'), (3, 'Editor'), (2, 'Author'), (4, 'Admin')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('80b5a670-3f25-450d-a93c-a73e1d6c932e'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
