# Generated by Django 3.2.4 on 2021-07-22 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_auto_20210722_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(3, 'Editor'), (2, 'Author'), (1, 'Reader'), (4, 'Admin')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('13af8e54-aa52-40cb-a917-5dc3752ab57e'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
