# Generated by Django 3.2.4 on 2021-07-23 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0004_auto_20210722_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'Reader'), (2, 'Author'), (4, 'Admin'), (3, 'Editor')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7cbe9354-3a23-47ad-a7c9-cd9ce19c618e'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
