# Generated by Django 3.2.4 on 2021-07-27 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_auto_20210724_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(4, 'Admin'), (2, 'Author'), (1, 'Reader'), (3, 'Editor')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3926b275-7bd0-46ba-9125-c1e32747cf33'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
