# Generated by Django 3.2.4 on 2021-07-28 21:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0007_auto_20210727_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(1, 'Reader'), (4, 'Admin'), (2, 'Author'), (3, 'Editor')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e048be81-8d04-4f8d-85ae-8dab339e3084'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
