# Generated by Django 3.2.4 on 2021-07-29 20:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210728_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Admin'), (3, 'Editor'), (2, 'Author'), (1, 'Reader')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('7bcd3bee-5b6c-4aca-8167-dfa619a62463'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
