# Generated by Django 3.2.4 on 2021-07-29 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210729_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reader'), (4, 'Admin'), (2, 'Author'), (3, 'Editor')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5e6bec30-e5b3-40e6-9021-52707aca9645'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
