# Generated by Django 3.2.4 on 2021-08-06 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_auto_20210729_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(3, 'Editor'), (2, 'Author'), (1, 'Reader'), (4, 'Admin')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ffccaf89-6e67-4063-b0f0-8af155610a54'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
