# Generated by Django 3.2.4 on 2021-08-09 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0014_auto_20210810_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(3, 'Editor'), (2, 'Author'), (1, 'Reader'), (4, 'Admin')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('c0ea47fc-6f9d-4933-81f7-31160bc05777'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
