# Generated by Django 3.2.4 on 2021-08-12 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0016_auto_20210810_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(3, 'Editor'), (2, 'Author'), (1, 'Reader'), (4, 'Admin')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('95f53295-8f57-4274-88f5-75919299f84b'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
