# Generated by Django 3.2.4 on 2021-08-13 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0017_auto_20210812_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(4, 'Admin'), (2, 'Author'), (3, 'Editor'), (1, 'Reader')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9d89d605-f2b7-44d5-8ee2-dcd7653f70f8'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
