# Generated by Django 3.2.4 on 2021-08-19 00:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0019_auto_20210815_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(2, 'Author'), (4, 'Admin'), (1, 'Reader'), (3, 'Editor')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1d1ab74a-4ada-414d-8a99-dba7651adfde'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
