# Generated by Django 3.2.4 on 2021-08-24 20:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0020_auto_20210819_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True,
                                                   choices=[(4, 'Admin'), (1, 'Reader'), (2, 'Author'), (3, 'Editor')],
                                                   default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('63bc649c-59ed-496e-a37a-df0575befb63'), editable=False,
                                   unique=True, verbose_name='Public identifier'),
        ),
    ]
