# Generated by Django 3.2.7 on 2021-09-05 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20210905_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, 'Author'), (3, 'Editor'), (4, 'Admin'), (1, 'Reader')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('85c0f7e1-0175-4d23-a577-93835bf23968'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
