# Generated by Django 3.2.7 on 2021-09-05 18:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210905_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reader'), (2, 'Author'), (3, 'Editor'), (4, 'Admin')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('3f6a9d72-f045-49a0-b2af-36d2dd620465'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
