# Generated by Django 3.2.7 on 2021-09-13 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20210908_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Reader'), (2, 'Author'), (4, 'Admin'), (3, 'Editor')], default=1, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('33670713-fcb4-42bf-8adc-32d95ff99e54'), editable=False, unique=True, verbose_name='Public identifier'),
        ),
    ]
