# Generated by Django 3.2.4 on 2021-08-09 23:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='love',
            field=models.ManyToManyField(blank=True, related_name='comment_love', to=settings.AUTH_USER_MODEL),
        ),
    ]
