# Generated by Django 3.2.4 on 2021-08-09 23:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('bookitem', '0002_comment_love'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
