# Generated by Django 3.2.4 on 2021-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookitem', '0006_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='VIP chapter'),
        ),
    ]
