# Generated by Django 3.2.7 on 2021-09-05 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookitem', '0007_chapter_is_vip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_short_description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_status',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='bookitem.bookcategory', verbose_name='book type'),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=150, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Book title'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
    ]
