# Generated by Django 3.2.7 on 2021-12-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookitem', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pool_total', models.FloatField(default=0)),
                ('Book_pool', models.FloatField(default=0)),
                ('Chapter_Pool', models.FloatField(default=0)),
                ('Donation_total', models.FloatField(default=0)),
                ('Donation_count', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Author_Pool',
                'verbose_name_plural': 'Author_Pools',
                'db_table': 'Author_Pool',
            },
        ),
        migrations.CreateModel(
            name='Income_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('Purchase Chapter', 'Purchase Chapter'), ('Donation', 'Donation'), ('Transfer', 'Transfer')], default=None, max_length=20)),
                ('Amount', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Income_History',
                'verbose_name_plural': 'Income_Histories',
                'db_table': 'Income_History',
            },
        ),
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('Purchase_Time', models.DateTimeField(auto_now_add=True)),
                ('New_balance', models.FloatField(default=0)),
                ('Transaction_type', models.CharField(choices=[('Transfer', 'Transfer'), ('Purchased Chapter', 'Purchased Chapter'), ('Purchased item', 'Purchased item'), ('Donation', 'Donation')], default=None, max_length=20)),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter_Purchased', to='bookitem.chapter', verbose_name='Chapter')),
                ('item', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.top_up_item')),
            ],
            options={
                'verbose_name': 'Transaction_History',
                'verbose_name_plural': 'Transaction_Histories',
                'db_table': 'Transaction_History',
            },
        ),
    ]
