# Generated by Django 3.2.7 on 2021-09-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookitem', '0009_alter_chapter_book'),
        ('product', '0006_auto_20210905_1819'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('unpaid', 'unpaid'), ('completed', 'completed'), ('cancelled', 'Cancelled')], default='unpaid', max_length=20)),
                ('Purchase_Time', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter_Purchased', to='bookitem.chapter', verbose_name='Chapter')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.top_up_item')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
