# Generated by Django 3.2.7 on 2021-09-08 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookitem', '0009_alter_chapter_book'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Type', models.CharField(choices=[('Purchase Chapter', 'Purchase Chapter'), ('Donation', 'Donation'), ('Others', 'Others')], default='Others', max_length=20)),
                ('Author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Author_ID', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chapter_Income', to='bookitem.chapter', verbose_name='Chapter')),
                ('from_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer_ID', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction_history')),
            ],
        ),
    ]
