# Generated by Django 3.2.7 on 2021-09-08 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_income_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author_Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pool_total', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Pool_User_ID', to=settings.AUTH_USER_MODEL)),
                ('History', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transactions.income_history')),
            ],
            options={
                'verbose_name': 'Author_Pool',
                'verbose_name_plural': 'Author_Pools',
                'db_table': 'Author_Pool',
            },
        ),
    ]
