# Generated by Django 3.2.7 on 2021-09-08 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0003_author_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('Donation_count', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Donation_User', to=settings.AUTH_USER_MODEL)),
                ('History', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transactions.income_history')),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'db_table': 'Donation',
            },
        ),
    ]
