# Generated by Django 3.2.7 on 2021-09-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_user_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='author_pool',
            name='Donation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author_pool',
            name='Donation_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='New_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='User_Donation',
        ),
    ]
