# Generated by Django 3.2.7 on 2021-09-08 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20210908_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income_history',
            options={'verbose_name': 'Income_History', 'verbose_name_plural': 'Income_Histories'},
        ),
        migrations.AlterModelOptions(
            name='transaction_history',
            options={'verbose_name': 'Transaction_History', 'verbose_name_plural': 'Transaction_Histories'},
        ),
        migrations.AddField(
            model_name='transaction_history',
            name='Transaction_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Purchased Chapter', 'Purchased Chapter'), ('Donation', 'Donation')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='income_history',
            name='Type',
            field=models.CharField(choices=[('Purchase Chapter', 'Purchase Chapter'), ('Donation', 'Donation'), ('Transfer', 'Transfer')], default=None, max_length=20),
        ),
        migrations.AlterModelTable(
            name='income_history',
            table='Income_History',
        ),
        migrations.AlterModelTable(
            name='transaction_history',
            table='Transaction_History',
        ),
    ]
