# Generated by Django 3.2.7 on 2021-09-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_auto_20210908_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='TO_USER', to=settings.AUTH_USER_MODEL),
        ),
    ]
