# Generated by Django 3.2.7 on 2021-09-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210905_1819'),
        ('transactions', '0008_auto_20210910_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='item',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.top_up_item'),
        ),
    ]
