# Generated by Django 3.2.7 on 2021-09-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_history_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='income_history',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
    ]
