# Generated by Django 3.2.7 on 2021-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_alter_transaction_history_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
