# Generated by Django 3.2.7 on 2021-09-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_history_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author_pool',
            name='History',
        ),
    ]
