# Generated by Django 3.2.7 on 2021-09-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_remove_author_pool_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_pool',
            name='Book_pool',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='author_pool',
            name='Chapter_Pool',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='author_pool',
            name='Donation_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='author_pool',
            name='Donation_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='author_pool',
            name='Pool_total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='income_history',
            name='Amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='New_balance',
            field=models.FloatField(default=0),
        ),
    ]
